snubuddy/urls.py
# -8_ coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from application import views as application_views
from base import views as base_views
from matching import views as matching_views
from korean import views as korean_views


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^upload/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}),

    url(r'^$', base_views.index, name='index'),
    url(r'^account/register/$',
        base_views.register,
        name='account_register'),
    url(r'^account/setting/$',
        base_views.setting,
        name='account_setting'),
    url(r'^account/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'account/login.html'}),
    url(r'^account/logout/$', 'django.contrib.auth.views.logout',
        kwargs={'next_page': '/'}),

    url(r'^application/$',
        application_views.index,
        name='application_index'),
    url(r'^application/register/$',
        application_views.register,
        name='application_register'),
    url(r'^application/register_finish/$',
        application_views.register_finish,
        name='application_register_finish'),
    url(r'^application/list/$',
        application_views.list,
        name='application_list'),
    url(r'^application/download/$',
        application_views.download,
        name='application_download'),
    url(r'^application/accept/(?P<application_id>\d+)/$',
        application_views.accept,
        name='application_accept'),

    url(r'^matching/$',
        matching_views.list,
        name='matching_list'),
    url(r'^matching/register/$',
        matching_views.register,
        name='matching_register'),
    url(r'^matching/view/(?P<id>\d+)/$',
        matching_views.view,
        name='matching_view'),
    url(r'^matching/register/(?P<id>\d+)/$',
        matching_views.register_foreigner,
        name='matching_register_foreigner'),
    url(r'^matching/register_full/$',
        matching_views.register_full,
        name='matching_register_full'),
    url(r'^matching/delete/(?P<id>\d+)/$',
        matching_views.delete,
        name='matching_delete'),
    url(r'^matching/delete/bye/(?P<id>\d+)/$',
        matching_views.delete_bye,
        name='matching_delete_bye'),

    url(r'^korean/korean_list/$',
        korean_views.korean_list,
        name='korean_korean_list'),
    url(r'^korean/full_list/$',
        korean_views.full_list,
        name='korean_full_list'),
    url(r'^korean/make_member/$',
        korean_views.make_member,
        name='korean_make_member'),

    url(r'^evaluation/$',
        korean_views.evaluation_status,
        name='evaluation_status'),

    url(r'^evaluation/personal_activity/$',
        korean_views.add_personal_activity,
        name='evaluation_add_personal_activity'),
    url(r'^evaluation/group_activity/$',
        korean_views.add_group_activity,
        name='evaluation_add_group_activity'),
    url(r'^evaluation/team_activity/$',
        korean_views.add_team_activity,
        name='evaluation_add_team_activity'),

    url(r'^evaluation/group_activity/(\d+)/$',
        korean_views.modify_group_activity,
        name='evaluation_modify_group_activity'),
    url(r'^evaluation/team_activity/(\d+)/$',
        korean_views.modify_team_activity,
        name='evaluation_modify_team_activity'),

    url(r'^evaluation/personal_activity/remove/(\d+)/$',
        korean_views.remove_personal_activity,
        name='evaluation_remove_personal_activity'),
    url(r'^evaluation/group_activity/remove/(\d+)/$',
        korean_views.remove_group_activity,
        name='evaluation_remove_group_activity'),
    url(r'^evaluation/team_activity/remove/(\d+)/$',
        korean_views.remove_team_activity,
        name='evaluation_remove_team_activity'),

    url(r'^evaluation/personal_report/$',
        korean_views.add_personal_report,
        name='evaluation_add_personal_report'),
    url(r'^evaluation/personal_report/(\d+)/$',
        korean_views.view_personal_report,
        name='evaluation_view_personal_report'),

    url(r'^evaluation/group_report/$',
        korean_views.add_group_report,
        name='evaluation_add_group_report'),
    url(r'^evaluation/group_report/(\d+)/$',
        korean_views.view_group_report,
        name='evaluation_view_group_report'),

    url(r'^evaluation/team_report/$',
        korean_views.add_team_report,
        name='evaluation_add_team_report'),
    url(r'^evaluation/team_report/(\d+)/$',
        korean_views.view_team_report,
        name='evaluation_view_team_report'),

    url(r'^evaluation/SECRET/$',
        korean_views.secret,
        name='evaluation_secret'),
    url(r'^evaluation/SECRET/(\d+)/$',
        korean_views.secret,
        name='evaluation_secret'),
    url(r'^evaluation/check/(\d+)/$',
        korean_views.check_evaluation,
        name='evaluation_check_evaluation'),
    url(r'^evaluation/personal_confirm/(\d+)/$',
        korean_views.personal_confirm,
        name='evaluation_personal_confirm'),
    url(r'^evaluation/group_confirm/(\d+)/$',
        korean_views.group_confirm,
        name='evaluation_group_confirm'),

    url(r'^evaluation/calculate/(\d+)/$',
        korean_views.calculate_score,
        name='evaluation_calculate_score'),
    url(r'^evaluation/ranking/$',
        korean_views.ranking_score,
        name='evaluation_ranking_score'),

    url(r'^mailing/add/$',
        base_views.mailing_add,
        name='mailing_add'),
    url(r'^mailing/finish/$',
        base_views.mailing_add_finish,
        name='mailing_add_finish'),
    url(r'^mailing/list/$',
        base_views.mailing_list,
        name='mailing_list'),
)

base/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User


# Common
class Season(models.Model):
    """Stores season"""
    year = models.IntegerField(null=False)
    semester = models.IntegerField(null=False)
    is_this_season = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u' '.join([u'%s년' % self.year,
                          u'%s학기' % self.semester,
                          u'(이번학기)' if self.is_this_season else u''])


class Country(models.Model):
    name = models.CharField(max_length=64, null=False, unique=True)

    def __unicode__(self):
        return u'%s' % self.name


class Language(models.Model):
    name = models.CharField(max_length=64, null=False, unique=True)

    def __unicode__(self):
        return u'%s' % self.name


# User
class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    user = models.OneToOneField(User, related_name='profile')
    korean_name = models.CharField(max_length=64, blank=True, null=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=False)
    birth = models.DateField(null=False)
    country = models.ForeignKey(Country, null=False)

    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class UserSeason(models.Model):
    ADMIN = 'A'
    KOREAN = 'K'
    FOREIGNER = 'F'
    USER_TYPE_CHOICES = (
        (ADMIN, u'운영진'),
        (KOREAN, u'한국인 버디'),
        (FOREIGNER, u'외국인 버디'),
    )

    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    user_type = models.CharField(max_length=1, choices=USER_TYPE_CHOICES, null=False)

    def __unicode__(self):
        return u'%s - %s %s' % (self.user.profile, self.season,
            dict(self.USER_TYPE_CHOICES)[self.user_type])

class Mailing(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False)
    email = models.CharField(max_length=256, blank=False, null=False)

    def __unicode__(self):
        return u'%s - %s' % (self.name, self.email)

matching/models.py
from django.db import models
from django.contrib.auth.models import User

from base.models import Season, Language


# Buddy Matching
class Matching(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    Both = 'B'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (Both, 'Both'),
    )

    user = models.ForeignKey(User)
    season = models.ForeignKey(Season)
    major = models.CharField(max_length=64, null=False)
    hobby = models.CharField(max_length=128, null=False)
    interest = models.CharField(max_length=128, null=False)
    self_introduction = models.TextField(null=False)
    comment = models.TextField(null=False)

    gender_preference = models.CharField(
        max_length=1, choices=GENDER_CHOICES, null=True)
    max_buddy_number = models.IntegerField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)


class MatchingLanguage(models.Model):
    matching = models.ForeignKey(Matching)
    language = models.ForeignKey(Language)
    level = models.IntegerField(null=False)

    def __unicode__(self):
        return u'%s %s %s' % (self.matching, self.language, self.level)


class MatchingConnection(models.Model):
    korean_matching = models.ForeignKey(Matching, related_name='korean')
    foreign_matching = models.ForeignKey(Matching, related_name='foreign')

    def __unicode__(self):
        return u'%s - %s' % (self.korean_matching, self.foreign_matching)

matching/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms
from django.utils.safestring import mark_safe
from django.template.loader import render_to_string

from base.models import Language
from matching.models import Matching


class LanguageWidget(forms.Widget):
    template_name = 'widget/language_list.html'

    def render(self, name, value, attrs=None):
        context = {
            'language_list': Language.objects.order_by('name')
        }
        return mark_safe(render_to_string(self.template_name, context))


class MatchingKoreanForm(ModelForm):
    language = forms.Field(widget=LanguageWidget, required=False)

    class Meta:
        model = Matching
        exclude = ('user', 'season')
        labels = {}
        help_texts = {}

    def is_valid(self):
        valid = super(MatchingKoreanForm, self).is_valid()

        try:
            languages = self.data.getlist('language[]')

            for item in languages:
                if Language.objects.filter(id=int(item)).count() != 1:
                    raise

            language_levels = map(int, self.data.getlist('language_level[]'))
            if max(language_levels) > 4 or min(language_levels) < 1:
                raise

            if len(languages) != len(language_levels):
                raise
        except:
            self.add_error('language', 'Something wrong with this field')
            valid = False

        return valid


class MatchingForeignerForm(ModelForm):
    language = forms.Field(widget=LanguageWidget, required=False)

    class Meta:
        model = Matching
        exclude = ('user', 'season', 'gender_preference', 'max_buddy_number')
        labels = {}
        help_texts = {}

    def is_valid(self):
        valid = super(MatchingForeignerForm, self).is_valid()

        try:
            languages = self.data.getlist('language[]')
            print languages
            for item in languages:
                if Language.objects.filter(id=int(item)).count() != 1:
                    raise

            language_levels = map(int, self.data.getlist('language_level[]'))
            if max(language_levels) > 4 or min(language_levels) < 1:
                raise

            if len(languages) != len(language_levels):
                raise
        except:
            self._errors['language'] = ['Something wrong with this field']
            return False

        return valid

base/views.py
# -*- coding: utf-8 -*-

import os
import mimetypes

from StringIO import StringIO

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.servers.basehttp import FileWrapper
from django.http import HttpResponse, HttpResponseForbidden

from base import queries
from base.models import Mailing
from base.forms import RegistrationForm, SettingsForm, MailingForm
from base.decorators import admin_required


def index(request):
    return render(request, 'index.html', {})


def register(request):
    form = RegistrationForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        #user = authenticate(username=form.cleaned_data['username'],
        #                    password=form.cleaned_data['password1'])
        #login(request, user)
        return redirect('/account/login/')

    return render(request, 'account/register.html', {
        'form': form
    })


@login_required
def setting(request):
    user = request.user
    form = SettingsForm(request.POST or None,
                        initial={'first_name': user.first_name,
                                 'last_name': user.last_name,
                                 'email': user.email,
                                 'korean_name': user.profile.korean_name,
                                 'gender': user.profile.gender,
                                 'birth': user.profile.birth,
                                 'country': user.profile.country})
    form.user = user

    if request.method == 'POST' and form.is_valid():
        form.save(user)
        return redirect(index)

    return render(request, 'account/setting.html', {
        'form': form
    })


@login_required
def personal_list(request):
    activities = queries.get_personal_activities(request.user)
    return render(request, 'personal/list.html', {
        'activities': activities
    })


@login_required
def personal_get_photo(request, personal_id):
    activity = queries.get_personal_activity(personal_id)
    if activity.user != request.user:
        return HttpResponseForbidden()
    image = StringIO(file(activity.photo.path, 'rb').read())

    mimetype = mimetypes.guess_type(os.path.basename(activity.photo.name))[0]
    return HttpResponse(image.read(), mimetype)


@login_required
def personal_add(request):
    if request.method == 'POST':
        form = PersonalActivityForm(request.POST, request.FILES)
        if form.is_valid():
            activity = form.save(commit=False)
            activity.user = request.user
            activity.save()
            return redirect(personal_list)
    else:
        form = PersonalActivityForm()

    return render(request, 'personal/add.html', {
        'form': form
    })


@login_required
def personal_delete(request, personal_id):
    activity = queries.get_personal_activity(personal_id)
    if activity.user != request.user:
        return HttpResponseForbidden()
    activity.delete()
    return redirect(personal_list)


def mailing_add(request):
    if request.method == 'POST':
        form = MailingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(mailing_add_finish)
    else:
        form = MailingForm()

    return render(request, 'mailing/add.html', {
        'form': form
    })


def mailing_add_finish(request):
    return render(request, 'mailing/finish.html', {
    })


@login_required
@admin_required
def mailing_list(request):
    mailings = Mailing.objects.all()
    return render(request, 'mailing/list.html', {
        'mailings': mailings
    })

templates/matching/base.html
{% extends "base.html" %}

{% block body_class %}matching{% endblock %}

templates/matching/buddy_table.html
{% load filters %}

<table class="buddyTable table">
    <tr>
        <th class="col-sm-3">Name</th>
        <td class="col-sm-9">{{ matching.user.first_name }} {{ matching.user.last_name }}</td>
    </tr>

    <tr>
        <th>E-Mail</th>
        <td>{{ matching.user.email }}</td>
    </tr>

    <tr>
        <th>Gender</th>
        <td>{{ matching.user.profile.get_gender_display }}</td>
    </tr>

    <tr>
        <th>Age</th>
        <td>{{ matching.user.profile.birth|age }}</td>
    </tr>

    <tr>
        <th>Major</th>
        <td>{{ matching.major }}</td>
    </tr>

    <tr>
        <th>Hobby</th>
        <td>{{ matching.hobby }}</td>
    </tr>

    <tr>
        <th>Interest</th>
        <td>{{ matching.interest }}</td>
    </tr>

    <tr>
        <th>Nationality</th>
        <td>{{ matching.user.profile.country }}</td>
    </tr>

    <tr>
        <th>Language</th>
        <td>
            {% for item in languages %}
            {{ item.language.name }}, {{ item.level|get_level_display }}
            {% if not forloop.last %}<br>{% endif %}
            {% endfor %}
        </td>
    </tr>

    <tr>
        <th>Self-Introduction</th>
        <td>{{ matching.self_introduction }}</td>
    </tr>

    {% if matching.user|is_korean %}
    <tr>
        <th>Max # of Buddies</th>
        <td>{{ matching|get_count_matched_buddies }} / <strong>Max : {{ matching.max_buddy_number }}</strong></td>
    </tr>

    <tr>
        <th>Buddy Gender Preference</th>
        <td>{{ matching.get_gender_preference_display }}</td>
    </tr>
    {% endif %}

    <tr>
        <th>Comment</th>
        <td>{{ matching.comment }}</td>
    </tr>

    <tr>
        {% comment %}
        <td class="delete">{% ifequal user matching.user %}<a href="/matching/delete/{{ matching.id }}/" class="btn btn-danger">Delete</a>{% endifequal %}</td>
        <td class="be_a_buddy">
        
        {% if matching.user|is_korean %}
        {% if not user|is_korean %}
        {% if user|is_new_buddy %}
            <a href="/matching/register/{{ matching.id }}/" class="btn btn-info">Be a Buddy</a>
        {% endif %}
        {% endif %}
        {% endif %}
        </td>
        {% endcomment %}
    </tr>
</table>

templates/matching/delete.html
{% extends "matching/base.html" %}
{% load filters %}

{% block content %}
<div class="container">
    <div class="row">

        <h1 class="page-header">Delete Buddy Profile</h1>

        <p>
            Please check again..
        </p>
        <p>
            <a href="/matching/delete/bye/{{ matching.id }}/" class="btn btn-danger">Delete!</a>
        </p>

        <table id="BuddyTable" class="table">
            <tr>
                <th class="col-sm-3">Name</th>
                <td class="col-sm-9">{{ matching.user.first_name }} {{ matching.user.last_name }}</td>
            </tr>

            <tr>
                <th>Gender</th>
                <td>{{ matching.user.profile.get_gender_display }}</td>
            </tr>

            <tr>
                <th>Age</th>
                <td>{{ matching.user.profile.birth|age }}</td>
            </tr>

            <tr>
                <th>Major</th>
                <td>{{ matching.major }}</td>
            </tr>

            <tr>
                <th>Hobby</th>
                <td>{{ matching.hobby }}</td>
            </tr>

            <tr>
                <th>Interest</th>
                <td>{{ matching.interest }}</td>
            </tr>

            <tr>
                <th>Nationality</th>
                <td>{{ matching.user.profile.country }}</td>
            </tr>

            <tr>
                <th>Language</th>
                <td> ??? </td>
            </tr>

            <tr>
                <th>Self-Introduction</th>
                <td>{{ matching.self_introduction }}</td>
            </tr>

            <tr>
                <th>Max # of Buddies</th>
                <td>{{ matching|get_count_matched_buddies }} / <strong>Max : {{ matching.max_buddy_number }}</strong></td>
            </tr>

            <tr>
                <th>Buddy Gender Preference</th>
                <td>{{ matching.get_gender_preference_display }}</td>
            </tr>

            <tr>
                <th>Comment</th>
                <td>{{ matching.comment }}</td>
            </tr>

            <tr>
            </tr>
        </table>
    </div>
</div>
{% endblock %}

templates/matching/list.html
{% extends "matching/base.html" %}
{% load filters %}

{% block content %}
<div class="container">
    <h1 class="page-header">Buddy List</h1>
    <table id="BuddyTable" class="table table-condensed table-striped table-center">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Buddy Gender<br>Preference</th>
                <th>Age</th>
                <th>Major</th>
                <th>Nationality</th>
                <th>Matched Buddies</th>
                <th>Details</th>
            </tr>
        </thead>

        <tbody>
        {% for item in matching_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.user.first_name }} {{ item.user.last_name }}</td>
            <td>{{ item.user.profile.get_gender_display }}</td>
            <td>{{ item.get_gender_preference_display }}</td>
            <td>{{ item.user.profile.birth|age }}</td>
            <td>{{ item.major }}</td>
            <td>{{ item.user.profile.country }}</td>
            <td>{{ item|get_count_matched_buddies }} / {{ item.max_buddy_number }}</td>
            <td><a class="btn btn-sm btn-primary" href="/matching/view/{{ item.id }}/">View</a></td>
        </tr>
        {% endfor %}
        </tbody>

        {% if user|is_korean %}
        <tfoot>
            <tr>
                <td colspan="9"><a class="btn btn-primary" href="/matching/register/">Registration for SNU Student</a></td>
            </tr>
        </tfoot>
        {% endif %}
    </table>
</div>
{% endblock %}

templates/matching/register.html
{% extends "matching/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">Buddy Matching Registration for Korean</h1>
    {% if exists %}
    <div class="alert alert-danger">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        You already submitted your matching!
        If you submit again, then newer one will <strong>replace</strong> old one.
    </p>
    {% endif %}
</div>

{% include "form_show.html" %}
{% endblock %}

templates/matching/register_finish.html
{% extends "matching/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">Buddy Matching Registration for Korean</h1>
    <p>
        Thank you :) Your profile was successfully saved on server! 
    </p>
</div>

{% endblock %}

templates/matching/register_foreigner.html
{% extends "matching/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">Buddy Matching with {{ matching.user.first_name }} {{ matching.user.last_name }}</h1>
    {% if exists %}
    <div class="alert alert-danger">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        You already submitted your profile!
        If you submit again, then newer one will <strong>replace</strong> old one.
    </p>
    {% endif %}
</div>

{% include "form_show.html" %}
{% endblock %}

templates/matching/register_foreigner_finish.html
{% extends "matching/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">Buddy Matching</h1>
    <p>
        Thank you :) Your profile was successfully saved on server! 
    </p>
</div>

{% endblock %}

templates/matching/register_full.html
{% extends "matching/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">Buddy Matching</h1>

    <div class="alert alert-danger">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        No available spots remained. :'(
    </div>
    <a class="btn btn-danger" href="/matching/">Go to list</a>
</div>

{% endblock %}

templates/matching/view.html
{% extends "matching/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">Buddy Profile</h1>

    {% include "matching/buddy_table.html" with matching=matching languages=languages %}
</div>

{% if foreigners %}
<div class="container">
    <h2 class="page-header">Applied Exchange Students</h2>

    {% for item in foreigners %}
    {% include "matching/buddy_table.html" with matching=item.0 languages=item.1 %}
    {% endfor %}
</div>
{% endif %}
{% endblock %}