snubuddy/urls.py
# -8_ coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from application import views as application_views
from base import views as base_views
from matching import views as matching_views
from korean import views as korean_views


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^upload/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}),

    url(r'^$', base_views.index, name='index'),
    url(r'^account/register/$',
        base_views.register,
        name='account_register'),
    url(r'^account/setting/$',
        base_views.setting,
        name='account_setting'),
    url(r'^account/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'account/login.html'}),
    url(r'^account/logout/$', 'django.contrib.auth.views.logout',
        kwargs={'next_page': '/'}),

    url(r'^application/$',
        application_views.index,
        name='application_index'),
    url(r'^application/register/$',
        application_views.register,
        name='application_register'),
    url(r'^application/register_finish/$',
        application_views.register_finish,
        name='application_register_finish'),
    url(r'^application/list/$',
        application_views.list,
        name='application_list'),
    url(r'^application/download/$',
        application_views.download,
        name='application_download'),
    url(r'^application/accept/(?P<application_id>\d+)/$',
        application_views.accept,
        name='application_accept'),

    url(r'^matching/$',
        matching_views.list,
        name='matching_list'),
    url(r'^matching/register/$',
        matching_views.register,
        name='matching_register'),
    url(r'^matching/view/(?P<id>\d+)/$',
        matching_views.view,
        name='matching_view'),
    url(r'^matching/register/(?P<id>\d+)/$',
        matching_views.register_foreigner,
        name='matching_register_foreigner'),
    url(r'^matching/register_full/$',
        matching_views.register_full,
        name='matching_register_full'),
    url(r'^matching/delete/(?P<id>\d+)/$',
        matching_views.delete,
        name='matching_delete'),
    url(r'^matching/delete/bye/(?P<id>\d+)/$',
        matching_views.delete_bye,
        name='matching_delete_bye'),

    url(r'^korean/korean_list/$',
        korean_views.korean_list,
        name='korean_korean_list'),
    url(r'^korean/full_list/$',
        korean_views.full_list,
        name='korean_full_list'),
    url(r'^korean/make_member/$',
        korean_views.make_member,
        name='korean_make_member'),

    url(r'^evaluation/$',
        korean_views.evaluation_status,
        name='evaluation_status'),

    url(r'^evaluation/personal_activity/$',
        korean_views.add_personal_activity,
        name='evaluation_add_personal_activity'),
    url(r'^evaluation/group_activity/$',
        korean_views.add_group_activity,
        name='evaluation_add_group_activity'),
    url(r'^evaluation/team_activity/$',
        korean_views.add_team_activity,
        name='evaluation_add_team_activity'),

    url(r'^evaluation/group_activity/(\d+)/$',
        korean_views.modify_group_activity,
        name='evaluation_modify_group_activity'),
    url(r'^evaluation/team_activity/(\d+)/$',
        korean_views.modify_team_activity,
        name='evaluation_modify_team_activity'),

    url(r'^evaluation/personal_activity/remove/(\d+)/$',
        korean_views.remove_personal_activity,
        name='evaluation_remove_personal_activity'),
    url(r'^evaluation/group_activity/remove/(\d+)/$',
        korean_views.remove_group_activity,
        name='evaluation_remove_group_activity'),
    url(r'^evaluation/team_activity/remove/(\d+)/$',
        korean_views.remove_team_activity,
        name='evaluation_remove_team_activity'),

    url(r'^evaluation/personal_report/$',
        korean_views.add_personal_report,
        name='evaluation_add_personal_report'),
    url(r'^evaluation/personal_report/(\d+)/$',
        korean_views.view_personal_report,
        name='evaluation_view_personal_report'),

    url(r'^evaluation/group_report/$',
        korean_views.add_group_report,
        name='evaluation_add_group_report'),
    url(r'^evaluation/group_report/(\d+)/$',
        korean_views.view_group_report,
        name='evaluation_view_group_report'),

    url(r'^evaluation/team_report/$',
        korean_views.add_team_report,
        name='evaluation_add_team_report'),
    url(r'^evaluation/team_report/(\d+)/$',
        korean_views.view_team_report,
        name='evaluation_view_team_report'),

    url(r'^evaluation/SECRET/$',
        korean_views.secret,
        name='evaluation_secret'),
    url(r'^evaluation/SECRET/(\d+)/$',
        korean_views.secret,
        name='evaluation_secret'),
    url(r'^evaluation/check/(\d+)/$',
        korean_views.check_evaluation,
        name='evaluation_check_evaluation'),
    url(r'^evaluation/personal_confirm/(\d+)/$',
        korean_views.personal_confirm,
        name='evaluation_personal_confirm'),
    url(r'^evaluation/group_confirm/(\d+)/$',
        korean_views.group_confirm,
        name='evaluation_group_confirm'),

    url(r'^evaluation/calculate/(\d+)/$',
        korean_views.calculate_score,
        name='evaluation_calculate_score'),
    url(r'^evaluation/ranking/$',
        korean_views.ranking_score,
        name='evaluation_ranking_score'),

    url(r'^mailing/add/$',
        base_views.mailing_add,
        name='mailing_add'),
    url(r'^mailing/finish/$',
        base_views.mailing_add_finish,
        name='mailing_add_finish'),
    url(r'^mailing/list/$',
        base_views.mailing_list,
        name='mailing_list'),
)

base/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User


# Common
class Season(models.Model):
    """Stores season"""
    year = models.IntegerField(null=False)
    semester = models.IntegerField(null=False)
    is_this_season = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u' '.join([u'%s년' % self.year,
                          u'%s학기' % self.semester,
                          u'(이번학기)' if self.is_this_season else u''])


class Country(models.Model):
    name = models.CharField(max_length=64, null=False, unique=True)

    def __unicode__(self):
        return u'%s' % self.name


class Language(models.Model):
    name = models.CharField(max_length=64, null=False, unique=True)

    def __unicode__(self):
        return u'%s' % self.name


# User
class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    user = models.OneToOneField(User, related_name='profile')
    korean_name = models.CharField(max_length=64, blank=True, null=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=False)
    birth = models.DateField(null=False)
    country = models.ForeignKey(Country, null=False)

    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class UserSeason(models.Model):
    ADMIN = 'A'
    KOREAN = 'K'
    FOREIGNER = 'F'
    USER_TYPE_CHOICES = (
        (ADMIN, u'운영진'),
        (KOREAN, u'한국인 버디'),
        (FOREIGNER, u'외국인 버디'),
    )

    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    user_type = models.CharField(max_length=1, choices=USER_TYPE_CHOICES, null=False)

    def __unicode__(self):
        return u'%s - %s %s' % (self.user.profile, self.season,
            dict(self.USER_TYPE_CHOICES)[self.user_type])

class Mailing(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False)
    email = models.CharField(max_length=256, blank=False, null=False)

    def __unicode__(self):
        return u'%s - %s' % (self.name, self.email)

korean/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

from base.models import Season


# Team
class Team(models.Model):
    season = models.ForeignKey(Season, null=False)
    name = models.CharField(max_length=64, null=False)

    def __unicode__(self):
        return u'%s - %s' % (self.season, self.name)


class UserTeam(models.Model):
    """Stores team information of Korean buddies"""
    team = models.ForeignKey(Team, null=False)
    user = models.ForeignKey(User, null=False)
    is_leader = models.BooleanField(default=False)

    def __unicode__(self):
        return u' '.join([unicode(self.team.season),
                          u'-', self.user.profile.korean_name,
                          u'-', unicode(self.team),
                          u'Leader' if self.is_leader else u''])


# Group
class BuddyGroup(models.Model):
    season = models.ForeignKey(Season, null=False)
    name = models.CharField(max_length=64, null=False)

    def __unicode__(self):
        return u'%s - %s' % (self.season, self.name)


class UserGroup(models.Model):
    """Stores group information of Korean buddies"""
    NOTHING = 0
    LEADER = 1
    SUBLEADER = 2
    LEADER_CHOICES = (
        (NOTHING, u''),
        (LEADER, u'조장'),
        (SUBLEADER, u'부조장'),
    )

    group = models.ForeignKey(BuddyGroup, null=False)
    user = models.ForeignKey(User, null=False)
    leader_type = models.IntegerField(
        choices=LEADER_CHOICES, default=0, null=False)

    def __unicode__(self):
        return u' '.join([unicode(self.group.season),
                          u'-', self.user.profile.korean_name,
                          u'-', unicode(self.group),
                          dict(self.LEADER_CHOICES)[self.leader_type]])


# Activity
class PersonalEvent(models.Model):
    CAMPUS = 0
    NEAR_CAMPUS = 1
    METROPOLITAN_AREA = 2
    OTHER = 3
    PLACE_CHOICES = (
        (CAMPUS, u'교내'),
        (NEAR_CAMPUS, u'학교 근처'),
        (METROPOLITAN_AREA, u'수도권'),
        (OTHER, u'수도권 외'),
    )

    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    title = models.CharField(max_length=256, null=False)
    start_date = models.DateField(null=False)
    place = models.CharField(max_length=256, null=False)
    place_type = models.IntegerField(choices=PLACE_CHOICES, null=False)
    photo = models.FileField(
        max_length=1024, upload_to='image/', null=False)
    is_language_exchange = models.BooleanField(default=False, null=False)
    is_confirm = models.BooleanField(default=False, null=False)

    def __unicode__(self):
        arr = [self.user.profile.korean_name,
               unicode(self.start_date),
               dict(self.PLACE_CHOICES)[self.place_type],
               unicode(self.place),
               unicode(self.title)]

        return u'/'.join(arr)


class GroupEvent(models.Model):
    CAMPUS = 0
    NEAR_CAMPUS = 1
    METROPOLITAN_AREA = 2
    OTHER = 3
    KOREAN = 4
    PLACE_CHOICES = (
        (CAMPUS, u'교내'),
        (NEAR_CAMPUS, u'학교 근처'),
        (METROPOLITAN_AREA, u'수도권'),
        (OTHER, u'수도권 외'),
        (KOREAN, u'한국인 모임'),
    )

    host = models.ForeignKey(User, null=False)
    group = models.ForeignKey(BuddyGroup, null=False)
    title = models.CharField(max_length=256, null=False)
    start_date = models.DateField(null=False)
    place = models.CharField(max_length=256, null=False)
    place_type = models.IntegerField(choices=PLACE_CHOICES, null=False)
    is_lunch = models.BooleanField(default=False, null=False)
    is_confirm = models.BooleanField(default=False, null=False)

    def __unicode__(self):
        arr = [unicode(self.group),
               unicode(self.start_date),
               dict(self.PLACE_CHOICES)[self.place_type],
               unicode(self.place),
               unicode(self.title)]

        return u'/'.join(arr)


class GroupAttend(models.Model):
    event = models.ForeignKey(GroupEvent, null=False)
    user = models.ForeignKey(User, null=False)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.event)])


class TeamEvent(models.Model):
    team = models.ForeignKey(Team, null=False)
    title = models.CharField(max_length=256, null=False)
    start_date = models.DateField(null=False)

    def __unicode__(self):
        arr = [unicode(self.team), unicode(self.start_date), self.title]

        return u'/'.join(arr)


class TeamAttend(models.Model):
    event = models.ForeignKey(TeamEvent, null=False)
    user = models.ForeignKey(User, null=False)
    score = models.FloatField(null=False)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.event), unicode(self.score)])


class PersonalReport(models.Model):
    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    question1 = models.TextField(null=False, blank=True)
    question2 = models.TextField(null=False, blank=True)
    question3 = models.TextField(null=False, blank=True)
    question4 = models.TextField(null=False, blank=True)
    question5 = models.TextField(null=False, blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.season),
                          unicode(self.month) + u'월'])


class TeamReport(models.Model):
    user = models.ForeignKey(User, null=False)
    team = models.ForeignKey(Team, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    created_datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u' '.join([unicode(self.team),
                          unicode(self.season),
                          unicode(self.month) + u'월'])


class TeamEvaluation(models.Model):
    A = 0
    B = 1
    C = 2
    D = 3
    GRADE_CHOICES = (
        (A, u'A'),
        (B, u'B'),
        (C, u'C'),
        (D, u'D'),
    )

    report = models.ForeignKey(TeamReport, null=False)
    user = models.ForeignKey(User, null=False)
    grade = models.IntegerField(choices=GRADE_CHOICES, null=False)
    reason = models.CharField(max_length=512, null=False, blank=True)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.report.season),
                          unicode(self.report.month) + u'월',
                          unicode(dict(self.GRADE_CHOICES)[self.grade])])


class GroupReport(models.Model):
    user = models.ForeignKey(User, null=False)
    group = models.ForeignKey(BuddyGroup, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    created_datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.group),
                          unicode(self.season),
                          unicode(self.month) + u'월'])


class GroupEvaluation(models.Model):
    report = models.ForeignKey(GroupReport, null=False)
    user = models.ForeignKey(User, null=False)
    score1 = models.IntegerField(null=False)
    score2 = models.IntegerField(null=False)
    reason = models.CharField(max_length=512, null=False, blank=True)

    def __unicode__(self):
        return u' '.join([unicode(self.report),
                          self.user.profile.korean_name])


class MonthlyScore(models.Model):
    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    count_personal_0 = models.IntegerField(default=0, null=False)
    count_personal_1 = models.IntegerField(default=0, null=False)
    count_personal_2 = models.IntegerField(default=0, null=False)
    count_personal_3 = models.IntegerField(default=0, null=False)
    count_group_0 = models.IntegerField(default=0, null=False)
    count_group_1 = models.IntegerField(default=0, null=False)
    count_group_2 = models.IntegerField(default=0, null=False)
    count_group_3 = models.IntegerField(default=0, null=False)
    count_group_4 = models.IntegerField(default=0, null=False)
    score_personal = models.FloatField(default=0, null=False)
    score_group = models.FloatField(default=0, null=False)
    score_team = models.FloatField(default=0, null=False)
    score_full = models.FloatField(default=0, null=False)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.month) + u'월',
                          unicode(self.score_personal),
                          unicode(self.score_group),
                          unicode(self.score_team)])

templates/evaluation/add_group_activity.html
{% extends "evaluation/base.html" %}

{% load filters %}

{% block content %}
<div class="container">
    <h1 class="page-header">조 활동 추가</h1>
</div>

{% if form.non_field_errors %}
<div class="container">
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %} 
        <p>{{ error }}</p>
        {% endfor %}
    </div>
</div>
{% endif %}

<div class="container">
    <form method="post" action="." class="form-horizontal" role="form">
        {% for field in form %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            <label for="{{ field.id }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">

                {% if field.name == 'is_lunch' %}
                <div class="checkbox">
                    <label>
                        {{ field }} LUNCH GATHERING!
                    </label>
                </div>
                {% else %}
                {{ field|add_class:"form-control" }}
                {% endif %}

                {% if field.help_text %}
                <p class="help-block">{{ field.help_text }}</p>
                {% endif %}

                {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <div class="form-group">
            <label class="col-sm-2 control-label">참가자</label>
            <div class="col-sm-10">
                <div class="row">
                {% for user, checked in members %}
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3 checkbox">
                        <label>
                            <input type="checkbox" {% if checked %}checked="checked"{% endif %} name="checked_ids" value="{{ user.id }}">
                        {{ user.profile.korean_name }}
                    </label>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                {% csrf_token %}
                <button type="submit" class="btn btn-default">Submit</button> 
            </div>
        </div>
    </form>
</div>

{% endblock %}

templates/evaluation/add_personal_activity.html
{% extends "evaluation/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">개인 활동 추가</h1>
</div>

{% include "form_file_show.html" %}
{% endblock %}

templates/evaluation/base.html
{% extends "base.html" %}

{% block body_class %}korean{% endblock %}

templates/evaluation/check.html
{% extends "evaluation/base.html" %}

{% block body_class %}korean{% endblock %}

{% block content %}
<div class="container">
    <h1 class="page-header">사회봉사 업무</h1>
    <a href="./?picture=true">사진 모두 열기(데이터 폭탄!)</a>
</div>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Personal Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Particulars</th>
                    <th>Remarks</th>
                    <th>Photo</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
            {% for event in personal_events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.user.profile.korean_name }}</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                    <td>{{ event.get_place_type_display }} ({{ event.place }})</td>
                    <td>
                        {% if picture %}
                        <img width="300px" src="{{ MEDIA_URL }}{{ event.photo }}">
                        {% else %}
                        <a href="{{ MEDIA_URL }}{{ event.photo }}">View</a>
                        {% endif %}
                    </td>
                    <td>
                        <a href="/evaluation/personal_confirm/{{ event.id }}/">{% if event.is_confirm %}확인 취소{% else %}확인{% endif %}</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Group Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Group</th>
                    <th>Date</th>
                    <th>Particulars</th>
                    <th>Remarks</th>
                    <th>Participants</th>
                    <th>Lunch?</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
            {% for event, koreans in group_infos %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.group.name }}</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                    <td>{{ event.get_place_type_display }} ({{ event.place }})</td>
                    <td>{% for korean in koreans %}{{ korean.user.profile.korean_name }} {% endfor %}</td>
                    <td>{% if event.is_lunch %}O{% endif %}</td>
                    <td>
                        <a href="/evaluation/group_confirm/{{ event.id }}/">{% if event.is_confirm %}확인 취소{% else %}확인{% endif %}</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/evaluation/secret.html
{% extends "evaluation/base.html" %}

{% block body_class %}korean{% endblock %}

{% block content %}
<div class="container">
    <h1 class="page-header">SECRET</h1>
    <a href="/evaluation/SECRET/?picture=true">사진 모두 열기(데이터 폭탄!)</a>
</div>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Personal Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Particulars</th>
                    <th>Remarks</th>
                    <th>Photo</th>
                </tr>
            </thead>

            <tbody>
            {% for event in personal_events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.user.profile.korean_name }}</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                    <td>{{ event.get_place_type_display }} ({{ event.place }})</td>
                    <td>
                        {% if picture %}
                        <img width="300px" src="{{ MEDIA_URL }}{{ event.photo }}">
                        {% else %}
                        <a href="{{ MEDIA_URL }}{{ event.photo }}">View</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Group Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Group(Host)</th>
                    <th>Date</th>
                    <th>Particulars</th>
                    <th>Remarks</th>
                    <th>Lunch?</th>
                </tr>
            </thead>

            <tbody>
            {% for event in group_events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.group.name }} ({{ event.host.profile.korean_name }})</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                    <td>{{ event.get_place_type_display }} ({{ event.place }})</td>
                    <td>{% if event.is_lunch %}O{% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Team Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Team</th>
                    <th>Date</th>
                    <th>Particulars</th>
                </tr>
            </thead>

            <tbody>
            {% for event in team_events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.team.name }}</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Personal Reports</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Month</th>
                    <th>View</th>
                </tr>
            </thead>

            <tbody>
            {% for report in personal_reports %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ report.user.profile.korean_name }}</td>
                    <td>{{ report.month }}</td>
                    <td><a href="/evaluation/personal_report/{{ report.id }}/">View</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Group Reports</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Group</th>
                    <th>User</th>
                    <th>Month</th>
                    <th>View</th>
                </tr>
            </thead>

            <tbody>
            {% for report in group_reports %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ report.group.name }}</td>
                    <td>{{ report.user.profile.korean_name }}</td>
                    <td>{{ report.month }}</td>
                    <td><a href="/evaluation/group_report/{{ report.id }}/">View</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Team Reports</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Team</th>
                    <th>Month</th>
                    <th>View</th>
                </tr>
            </thead>

            <tbody>
            {% for report in team_reports %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ report.team.name }}</td>
                    <td>{{ report.month }}</td>
                    <td><a href="/evaluation/team_report/{{ report.id }}/">View</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/evaluation/view_team_report.html
{% extends "evaluation/base.html" %}

{% load filters %}

{% block content %}
<div class="container">
    <h1 class="page-header">{{ report.month }}월 {{ report.team.name }}팀 활동 평가서 <small>작성자: {{ report.user.profile.korean_name }}</small></h1>
</div>

<div class="container">
    <table class="table table-center table-condensed table-striped">
        <thead>
            <tr>
                <th class="col-xs-2">Name</th>
                <th class="col-xs-2">Grade</th>
                <th class="col-xs-6">Reason</th>
            </tr>
        </thead>

        <tbody>
            {% for evaluation in evaluations %}
            <tr>
                <td>{{ evaluation.user.profile.korean_name }}</td>
                <td>{{ evaluation.get_grade_display }}</td>
                <td>{{ evaluation.reason }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}