snubuddy/urls.py
# -8_ coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from application import views as application_views
from base import views as base_views
from matching import views as matching_views
from korean import views as korean_views


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^upload/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}),

    url(r'^$', base_views.index, name='index'),
    url(r'^account/register/$',
        base_views.register,
        name='account_register'),
    url(r'^account/setting/$',
        base_views.setting,
        name='account_setting'),
    url(r'^account/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'account/login.html'}),
    url(r'^account/logout/$', 'django.contrib.auth.views.logout',
        kwargs={'next_page': '/'}),

    url(r'^application/$',
        application_views.index,
        name='application_index'),
    url(r'^application/register/$',
        application_views.register,
        name='application_register'),
    url(r'^application/register_finish/$',
        application_views.register_finish,
        name='application_register_finish'),
    url(r'^application/list/$',
        application_views.list,
        name='application_list'),
    url(r'^application/download/$',
        application_views.download,
        name='application_download'),
    url(r'^application/accept/(?P<application_id>\d+)/$',
        application_views.accept,
        name='application_accept'),

    url(r'^matching/$',
        matching_views.list,
        name='matching_list'),
    url(r'^matching/register/$',
        matching_views.register,
        name='matching_register'),
    url(r'^matching/view/(?P<id>\d+)/$',
        matching_views.view,
        name='matching_view'),
    url(r'^matching/register/(?P<id>\d+)/$',
        matching_views.register_foreigner,
        name='matching_register_foreigner'),
    url(r'^matching/register_full/$',
        matching_views.register_full,
        name='matching_register_full'),
    url(r'^matching/delete/(?P<id>\d+)/$',
        matching_views.delete,
        name='matching_delete'),
    url(r'^matching/delete/bye/(?P<id>\d+)/$',
        matching_views.delete_bye,
        name='matching_delete_bye'),

    url(r'^korean/korean_list/$',
        korean_views.korean_list,
        name='korean_korean_list'),
    url(r'^korean/full_list/$',
        korean_views.full_list,
        name='korean_full_list'),
    url(r'^korean/make_member/$',
        korean_views.make_member,
        name='korean_make_member'),

    url(r'^evaluation/$',
        korean_views.evaluation_status,
        name='evaluation_status'),

    url(r'^evaluation/personal_activity/$',
        korean_views.add_personal_activity,
        name='evaluation_add_personal_activity'),
    url(r'^evaluation/group_activity/$',
        korean_views.add_group_activity,
        name='evaluation_add_group_activity'),
    url(r'^evaluation/team_activity/$',
        korean_views.add_team_activity,
        name='evaluation_add_team_activity'),

    url(r'^evaluation/group_activity/(\d+)/$',
        korean_views.modify_group_activity,
        name='evaluation_modify_group_activity'),
    url(r'^evaluation/team_activity/(\d+)/$',
        korean_views.modify_team_activity,
        name='evaluation_modify_team_activity'),

    url(r'^evaluation/personal_activity/remove/(\d+)/$',
        korean_views.remove_personal_activity,
        name='evaluation_remove_personal_activity'),
    url(r'^evaluation/group_activity/remove/(\d+)/$',
        korean_views.remove_group_activity,
        name='evaluation_remove_group_activity'),
    url(r'^evaluation/team_activity/remove/(\d+)/$',
        korean_views.remove_team_activity,
        name='evaluation_remove_team_activity'),

    url(r'^evaluation/personal_report/$',
        korean_views.add_personal_report,
        name='evaluation_add_personal_report'),
    url(r'^evaluation/personal_report/(\d+)/$',
        korean_views.view_personal_report,
        name='evaluation_view_personal_report'),

    url(r'^evaluation/group_report/$',
        korean_views.add_group_report,
        name='evaluation_add_group_report'),
    url(r'^evaluation/group_report/(\d+)/$',
        korean_views.view_group_report,
        name='evaluation_view_group_report'),

    url(r'^evaluation/team_report/$',
        korean_views.add_team_report,
        name='evaluation_add_team_report'),
    url(r'^evaluation/team_report/(\d+)/$',
        korean_views.view_team_report,
        name='evaluation_view_team_report'),

    url(r'^evaluation/SECRET/$',
        korean_views.secret,
        name='evaluation_secret'),
    url(r'^evaluation/SECRET/(\d+)/$',
        korean_views.secret,
        name='evaluation_secret'),
    url(r'^evaluation/check/(\d+)/$',
        korean_views.check_evaluation,
        name='evaluation_check_evaluation'),
    url(r'^evaluation/personal_confirm/(\d+)/$',
        korean_views.personal_confirm,
        name='evaluation_personal_confirm'),
    url(r'^evaluation/group_confirm/(\d+)/$',
        korean_views.group_confirm,
        name='evaluation_group_confirm'),

    url(r'^evaluation/calculate/(\d+)/$',
        korean_views.calculate_score,
        name='evaluation_calculate_score'),
    url(r'^evaluation/ranking/$',
        korean_views.ranking_score,
        name='evaluation_ranking_score'),

    url(r'^mailing/add/$',
        base_views.mailing_add,
        name='mailing_add'),
    url(r'^mailing/finish/$',
        base_views.mailing_add_finish,
        name='mailing_add_finish'),
    url(r'^mailing/list/$',
        base_views.mailing_list,
        name='mailing_list'),
)

base/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User


# Common
class Season(models.Model):
    """Stores season"""
    year = models.IntegerField(null=False)
    semester = models.IntegerField(null=False)
    is_this_season = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u' '.join([u'%s년' % self.year,
                          u'%s학기' % self.semester,
                          u'(이번학기)' if self.is_this_season else u''])


class Country(models.Model):
    name = models.CharField(max_length=64, null=False, unique=True)

    def __unicode__(self):
        return u'%s' % self.name


class Language(models.Model):
    name = models.CharField(max_length=64, null=False, unique=True)

    def __unicode__(self):
        return u'%s' % self.name


# User
class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    user = models.OneToOneField(User, related_name='profile')
    korean_name = models.CharField(max_length=64, blank=True, null=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=False)
    birth = models.DateField(null=False)
    country = models.ForeignKey(Country, null=False)

    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class UserSeason(models.Model):
    ADMIN = 'A'
    KOREAN = 'K'
    FOREIGNER = 'F'
    USER_TYPE_CHOICES = (
        (ADMIN, u'운영진'),
        (KOREAN, u'한국인 버디'),
        (FOREIGNER, u'외국인 버디'),
    )

    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    user_type = models.CharField(max_length=1, choices=USER_TYPE_CHOICES, null=False)

    def __unicode__(self):
        return u'%s - %s %s' % (self.user.profile, self.season,
            dict(self.USER_TYPE_CHOICES)[self.user_type])

class Mailing(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False)
    email = models.CharField(max_length=256, blank=False, null=False)

    def __unicode__(self):
        return u'%s - %s' % (self.name, self.email)

korean/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

from base.models import Season


# Team
class Team(models.Model):
    season = models.ForeignKey(Season, null=False)
    name = models.CharField(max_length=64, null=False)

    def __unicode__(self):
        return u'%s - %s' % (self.season, self.name)


class UserTeam(models.Model):
    """Stores team information of Korean buddies"""
    team = models.ForeignKey(Team, null=False)
    user = models.ForeignKey(User, null=False)
    is_leader = models.BooleanField(default=False)

    def __unicode__(self):
        return u' '.join([unicode(self.team.season),
                          u'-', self.user.profile.korean_name,
                          u'-', unicode(self.team),
                          u'Leader' if self.is_leader else u''])


# Group
class BuddyGroup(models.Model):
    season = models.ForeignKey(Season, null=False)
    name = models.CharField(max_length=64, null=False)

    def __unicode__(self):
        return u'%s - %s' % (self.season, self.name)


class UserGroup(models.Model):
    """Stores group information of Korean buddies"""
    NOTHING = 0
    LEADER = 1
    SUBLEADER = 2
    LEADER_CHOICES = (
        (NOTHING, u''),
        (LEADER, u'조장'),
        (SUBLEADER, u'부조장'),
    )

    group = models.ForeignKey(BuddyGroup, null=False)
    user = models.ForeignKey(User, null=False)
    leader_type = models.IntegerField(
        choices=LEADER_CHOICES, default=0, null=False)

    def __unicode__(self):
        return u' '.join([unicode(self.group.season),
                          u'-', self.user.profile.korean_name,
                          u'-', unicode(self.group),
                          dict(self.LEADER_CHOICES)[self.leader_type]])


# Activity
class PersonalEvent(models.Model):
    CAMPUS = 0
    NEAR_CAMPUS = 1
    METROPOLITAN_AREA = 2
    OTHER = 3
    PLACE_CHOICES = (
        (CAMPUS, u'교내'),
        (NEAR_CAMPUS, u'학교 근처'),
        (METROPOLITAN_AREA, u'수도권'),
        (OTHER, u'수도권 외'),
    )

    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    title = models.CharField(max_length=256, null=False)
    start_date = models.DateField(null=False)
    place = models.CharField(max_length=256, null=False)
    place_type = models.IntegerField(choices=PLACE_CHOICES, null=False)
    photo = models.FileField(
        max_length=1024, upload_to='image/', null=False)
    is_language_exchange = models.BooleanField(default=False, null=False)
    is_confirm = models.BooleanField(default=False, null=False)

    def __unicode__(self):
        arr = [self.user.profile.korean_name,
               unicode(self.start_date),
               dict(self.PLACE_CHOICES)[self.place_type],
               unicode(self.place),
               unicode(self.title)]

        return u'/'.join(arr)


class GroupEvent(models.Model):
    CAMPUS = 0
    NEAR_CAMPUS = 1
    METROPOLITAN_AREA = 2
    OTHER = 3
    KOREAN = 4
    PLACE_CHOICES = (
        (CAMPUS, u'교내'),
        (NEAR_CAMPUS, u'학교 근처'),
        (METROPOLITAN_AREA, u'수도권'),
        (OTHER, u'수도권 외'),
        (KOREAN, u'한국인 모임'),
    )

    host = models.ForeignKey(User, null=False)
    group = models.ForeignKey(BuddyGroup, null=False)
    title = models.CharField(max_length=256, null=False)
    start_date = models.DateField(null=False)
    place = models.CharField(max_length=256, null=False)
    place_type = models.IntegerField(choices=PLACE_CHOICES, null=False)
    is_lunch = models.BooleanField(default=False, null=False)
    is_confirm = models.BooleanField(default=False, null=False)

    def __unicode__(self):
        arr = [unicode(self.group),
               unicode(self.start_date),
               dict(self.PLACE_CHOICES)[self.place_type],
               unicode(self.place),
               unicode(self.title)]

        return u'/'.join(arr)


class GroupAttend(models.Model):
    event = models.ForeignKey(GroupEvent, null=False)
    user = models.ForeignKey(User, null=False)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.event)])


class TeamEvent(models.Model):
    team = models.ForeignKey(Team, null=False)
    title = models.CharField(max_length=256, null=False)
    start_date = models.DateField(null=False)

    def __unicode__(self):
        arr = [unicode(self.team), unicode(self.start_date), self.title]

        return u'/'.join(arr)


class TeamAttend(models.Model):
    event = models.ForeignKey(TeamEvent, null=False)
    user = models.ForeignKey(User, null=False)
    score = models.FloatField(null=False)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.event), unicode(self.score)])


class PersonalReport(models.Model):
    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    question1 = models.TextField(null=False, blank=True)
    question2 = models.TextField(null=False, blank=True)
    question3 = models.TextField(null=False, blank=True)
    question4 = models.TextField(null=False, blank=True)
    question5 = models.TextField(null=False, blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.season),
                          unicode(self.month) + u'월'])


class TeamReport(models.Model):
    user = models.ForeignKey(User, null=False)
    team = models.ForeignKey(Team, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    created_datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u' '.join([unicode(self.team),
                          unicode(self.season),
                          unicode(self.month) + u'월'])


class TeamEvaluation(models.Model):
    A = 0
    B = 1
    C = 2
    D = 3
    GRADE_CHOICES = (
        (A, u'A'),
        (B, u'B'),
        (C, u'C'),
        (D, u'D'),
    )

    report = models.ForeignKey(TeamReport, null=False)
    user = models.ForeignKey(User, null=False)
    grade = models.IntegerField(choices=GRADE_CHOICES, null=False)
    reason = models.CharField(max_length=512, null=False, blank=True)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.report.season),
                          unicode(self.report.month) + u'월',
                          unicode(dict(self.GRADE_CHOICES)[self.grade])])


class GroupReport(models.Model):
    user = models.ForeignKey(User, null=False)
    group = models.ForeignKey(BuddyGroup, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    created_datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.group),
                          unicode(self.season),
                          unicode(self.month) + u'월'])


class GroupEvaluation(models.Model):
    report = models.ForeignKey(GroupReport, null=False)
    user = models.ForeignKey(User, null=False)
    score1 = models.IntegerField(null=False)
    score2 = models.IntegerField(null=False)
    reason = models.CharField(max_length=512, null=False, blank=True)

    def __unicode__(self):
        return u' '.join([unicode(self.report),
                          self.user.profile.korean_name])


class MonthlyScore(models.Model):
    user = models.ForeignKey(User, null=False)
    season = models.ForeignKey(Season, null=False)
    month = models.IntegerField(null=False)
    count_personal_0 = models.IntegerField(default=0, null=False)
    count_personal_1 = models.IntegerField(default=0, null=False)
    count_personal_2 = models.IntegerField(default=0, null=False)
    count_personal_3 = models.IntegerField(default=0, null=False)
    count_group_0 = models.IntegerField(default=0, null=False)
    count_group_1 = models.IntegerField(default=0, null=False)
    count_group_2 = models.IntegerField(default=0, null=False)
    count_group_3 = models.IntegerField(default=0, null=False)
    count_group_4 = models.IntegerField(default=0, null=False)
    score_personal = models.FloatField(default=0, null=False)
    score_group = models.FloatField(default=0, null=False)
    score_team = models.FloatField(default=0, null=False)
    score_full = models.FloatField(default=0, null=False)

    def __unicode__(self):
        return u' '.join([self.user.profile.korean_name,
                          unicode(self.month) + u'월',
                          unicode(self.score_personal),
                          unicode(self.score_group),
                          unicode(self.score_team)])

templates/foradmin/base.html
{% extends "base.html" %}

{% block body_class %}admin{% endblock %}

templates/foradmin/full_list.html
{% extends "foradmin/base.html" %}

{% load filters %}

{% block content %}
<div class="container">
    <h1 class="page-header">Full Buddy List</h1>
    {% for group, inner_info in infos %}
    <h2>{{ group.name }}</h2>
    <table class="table table-condensed table-center">
        <thead>
            <tr>
                <th>Type</th>
                <th>Name</th>
                <th>E-mail</th>
                <th>Gender</th>
                <th>Birth</th>
                <th>Nationality</th>
<!--                <th>SNU No.</th>
                <th>Facebook Info</th>-->
            </tr>
        </thead>

        <tbody>
            {% for usergroup, personal_buddies in inner_info %}
            <tr {% if usergroup.user|is_korean %}class="korean"{% endif %}>
                <td>Korean</td>
                <td>{{ usergroup.user.first_name }} {{ usergroup.user.last_name }}</td>
                <td>{{ usergroup.user.email }}</td>
                <td>{{ usergroup.user.profile.get_gender_display }}</td>
                <td>{{ usergroup.user.profile.birth|date:"y/m/d" }}</td>
                <td>{{ usergroup.user.profile.country }}</td>
<!--                <td></td>
                <td></td>-->
            </tr>
            {% for user, application in personal_buddies %}
            <tr {% if user|is_korean %}class="korean"{% endif %}>
                <td>{% if application.returning %}Return{% else %}NEW{% endif %}</td>
                <td>{{ user.first_name }} {{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.profile.get_gender_display }}</td>
                <td>{{ user.profile.birth|date:"y/m/d" }}</td>
                <td>{{ user.profile.country }}</td>
<!--                <td>{{ application.snu_id }}</td>
                <td title="{{ application.fb_name }}">{{ application.fb_email }}</td>-->
            </tr>
            {% endfor %}
            {% endfor %}
        </tbody>
    </table>
    {% endfor %}
    </div>
{% endblock %}

templates/foradmin/korean_list.html
{% extends "foradmin/base.html" %}

{% load filters %}

{% block content %}
<div class="container">
    <h1 class="page-header">Korean List</h1>
    <form action="/korean/make_member/" method="POST">
        {% csrf_token %}
    <table id="KoreanTable" class="table table-condensed table-striped table-center">
        <thead>
            <th></th>
            <th>#</th>
            <th>Name</th>
            <th>Korean Name</th>
            <th>Team</th>
            <th>Group</th>
            <th>Gender</th>
            <th>Birth</th>
            <th>Matching?</th>
        </thead>

        <tbody>
        {% for item in infos %}
            <tr>
                <td><input type="checkbox" name="checked_ids" value="{{ item.0.id }}"></td>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.0.first_name }} {{ item.0.last_name }}</td>
                <td>{{ item.0.profile.korean_name }}</td>
                <td>{{ item.2.team.name }}{% if item.2.is_leader %}팀장{% endif %}</td>
                <td>{{ item.3.group.name }} {{ item.3.get_leader_type_display }}</td>
                <td>{{ item.0.profile.get_gender_display }}</td>
                <td>{{ item.0.profile.birth|date:"m/d" }}</td>
                <td>{% if not item.1 %}X{% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>

        <tfoot>
            <tr>
                <th colspan="2">Team<br>Action</th>
                <td colspan="7">
                    {% for team in teams %}
                    <button class="btn btn-sm btn-primary" name="team" value="{{ team.id }}">{{ team.name }}</button>
                    {% endfor %}
                    <button class="btn btn-sm btn-danger" name="team" value="0">무소속</button>
                    <button class="btn btn-sm btn-warning" name="team_leader" value="1">팀장</button>
                </td>
            </tr>

            <tr>
                <th colspan="2">Group<br>Action</th>
                <td colspan="7">
                    {% for group in groups %}
                    <button class="btn btn-sm btn-primary" name="group" value="{{ group.id }}">{{ group.name }}</button>
                    {% endfor %}
                    <button class="btn btn-sm btn-warning" name="group_leader" value="1">조장</button>
                    <button class="btn btn-sm btn-warning" name="group_leader" value="2">부조장</button>
                </td>
            </tr>

        </tfoot>
    </table>
    </form>
</div>
{% endblock %}

templates/foradmin/ranking.html
{% extends "foradmin/base.html" %}

{% block content %}
<div class="container">
    <h2>Ranking</h2>
    
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Summary</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>이름</th>
                    <th>개인</th>
                    <th>조</th>
                    <th>팀</th>
                    <th>합</th>
                </tr>
            </thead>

            <tbody>
                {% for user, score in score_sum %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.profile.korean_name }}</td>
                    <td>{{ score.0 }}</td>
                    <td>{{ score.1 }}</td>
                    <td>{{ score.2 }}</td>
                    <td>{{ score.3 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    

    {% for infos in score_info %}
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">{{ infos.0.month }}월</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>월</th>
                    <th>개인</th>
                    <th>조</th>
                    <th>팀</th>
                    <th>합</th>
                </tr>
            </thead>

            <tbody>
                {% for info in infos %}
                {% if info.score_full > 0 %}
                <tr>
                    <td>{{ info.user.profile.korean_name }}</td>
                    <td>{{ info.score_personal }}</td>
                    <td>{{ info.score_group }}</td>
                    <td>{{ info.score_team }}</td>
                    <td>{{ info.score_full }}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/foradmin/secret.html
{% extends "foradmin/base.html" %}

{% block content %}
<div class="container">
    <h1 class="page-header">SECRET</h1>
    <a href="?picture=true">사진 모두 열기(데이터 폭탄!)</a>
</div>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Personal Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Particulars</th>
                    <th>Remarks</th>
                    <th>Photo</th>
                </tr>
            </thead>

            <tbody>
            {% for event in personal_events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.user.profile.korean_name }}</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                    <td>{{ event.get_place_type_display }} ({{ event.place }})</td>
                    <td>
                        {% if picture %}
                        <img width="300px" src="{{ MEDIA_URL }}{{ event.photo }}">
                        {% else %}
                        <a href="{{ MEDIA_URL }}{{ event.photo }}">View</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Group Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Group(Host)</th>
                    <th>Date</th>
                    <th>Particulars</th>
                    <th>Remarks</th>
                    <th>Lunch?</th>
                </tr>
            </thead>

            <tbody>
            {% for event in group_events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.group.name }} ({{ event.host.profile.korean_name }})</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                    <td>{{ event.get_place_type_display }} ({{ event.place }})</td>
                    <td>{% if event.is_lunch %}O{% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Team Activities</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Team</th>
                    <th>Date</th>
                    <th>Particulars</th>
                </tr>
            </thead>

            <tbody>
            {% for event in team_events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.team.name }}</td>
                    <td>{{ event.start_date|date:"m.d" }}</td>
                    <td>{{ event.title }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Personal Reports</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Month</th>
                    <th>View</th>
                </tr>
            </thead>

            <tbody>
            {% for report in personal_reports %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ report.user.profile.korean_name }}</td>
                    <td>{{ report.month }}</td>
                    <td><a href="/evaluation/personal_report/{{ report.id }}/">View</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Group Reports</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Group</th>
                    <th>User</th>
                    <th>Month</th>
                    <th>View</th>
                </tr>
            </thead>

            <tbody>
            {% for report in group_reports %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ report.group.name }}</td>
                    <td>{{ report.user.profile.korean_name }}</td>
                    <td>{{ report.month }}</td>
                    <td><a href="/evaluation/group_report/{{ report.id }}/">View</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title">Team Reports</h3></div>

        <table class="table table-condensed table-striped table-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Team</th>
                    <th>Month</th>
                    <th>View</th>
                </tr>
            </thead>

            <tbody>
            {% for report in team_reports %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ report.team.name }}</td>
                    <td>{{ report.month }}</td>
                    <td><a href="/evaluation/team_report/{{ report.id }}/">View</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}